# Generated by Django 5.0.6 on 2024-08-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('provincia', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=600)),
                ('mail_artista', models.CharField(max_length=200, null=True)),
                ('pagina_web_redes_sociales', models.CharField(max_length=300)),
                ('obras', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('técnica', models.CharField(max_length=50, null=True)),
                ('año', models.CharField(max_length=50, null=True)),
                ('tematica', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='artista',
        ),
    ]
