# Generated by Django 5.0.6 on 2024-08-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinal', '0002_artistas_obras_delete_artista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acerca_de_mi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='obras',
            name='dimensiones',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
