# Generated by Django 5.0.6 on 2024-08-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinal', '0003_acerca_de_mi_obras_dimensiones'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
