# Generated by Django 5.0.6 on 2024-08-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinal', '0004_obras_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='obra',
            field=models.ImageField(blank=True, null=True, upload_to='obras'),
        ),
        migrations.AlterField(
            model_name='artistas',
            name='obras',
            field=models.ImageField(blank=True, null=True, upload_to='obras'),
        ),
    ]
