# Generated by Django 5.0.6 on 2024-08-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfinal', '0006_remove_artistas_obras_remove_obras_obra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='autor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
